### ISSUE TITLE
AS a staffer, I want my hotel info private 

### ISSUE THREAD

**Issue by msg4real** [magfest/ubersystem#2995]
RoomAssignment and Room tables are being leaking into feed of DB changes

**Comment by RobRuana** [comment]
Related to #2909.

**Comment by kitsuta** [comment]
This was fixed by https://github.com/magfest/ubersystem/pull/3051, right?

**Comment by RobRuana** [comment]
Ah, we still show each attendees database changes on their "History" page. So, it's still kinda leaky.
